<a href="https://colab.research.google.com/github/karsarobert/Deep-Learning-2022/blob/main/10/PTE_DL10_SPAM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import LSTM, Dense,Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing import sequence
import pickle

In [ ]:
df = pd.read_csv("spam.csv", encoding="latin")

In [ ]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [ ]:
df = df[["v1","v2"]]

In [ ]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df["v1"].value_counts()

ham     4825
spam     747
Name: v1, dtype: int64

In [ ]:
# get X as feature and Y as target 

In [ ]:
lab_map = {"ham":0, "spam":1} #dict

In [ ]:
Y = df["v1"].map(lab_map).values

In [ ]:
Y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
X = df["v2"].values

In [ ]:
X

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [ ]:
# convert to sequences
# pad sequence
# train

In [ ]:
max_words = 1000
mytokenizer = Tokenizer(num_words=max_words,lower=True, split=" ") #tokenizáló beálítása

In [ ]:
mytokenizer.fit_on_texts(X) # tokenek létrehozása az X-ből

In [ ]:
len(mytokenizer.word_counts)

8920

In [ ]:
mytokenizer.word_counts

OrderedDict([('go', 280),
             ('until', 27),
             ('jurong', 1),
             ('point', 13),
             ('crazy', 15),
             ('available', 18),
             ('only', 218),
             ('in', 898),
             ('bugis', 7),
             ('n', 152),
             ('great', 115),
             ('world', 37),
             ('la', 7),
             ('e', 96),
             ('buffet', 2),
             ('cine', 7),
             ('there', 202),
             ('got', 239),
             ('amore', 1),
             ('wat', 99),
             ('ok', 287),
             ('lar', 38),
             ('joking', 6),
             ('wif', 27),
             ('u', 1172),
             ('oni', 4),
             ('free', 284),
             ('entry', 26),
             ('2', 515),
             ('a', 1433),
             ('wkly', 14),
             ('comp', 12),
             ('to', 2242),
             ('win', 75),
             ('fa', 4),
             ('cup', 8),
             ('final', 18),
        

In [ ]:
text_tokenized = mytokenizer.texts_to_sequences(X) # szövegből szekvenciák létrehozása

In [ ]:
text_tokenized

[[50, 469, 841, 751, 657, 64, 8, 89, 121, 349, 147, 67, 58, 144],
 [46, 336, 470, 6],
 [47,
  486,
  8,
  19,
  4,
  796,
  899,
  2,
  178,
  658,
  267,
  71,
  2,
  2,
  337,
  486,
  554,
  955,
  73,
  388,
  179,
  659,
  389],
 [6, 245, 152, 23, 379, 6, 140, 154, 57, 152],
 [1, 98, 107, 69, 487, 2, 956, 69, 218, 111, 471],
 [797,
  127,
  67,
  145,
  108,
  160,
  21,
  7,
  38,
  338,
  87,
  900,
  55,
  115,
  411,
  3,
  44,
  12,
  14,
  85,
  46,
  380,
  955,
  2,
  68,
  322,
  230,
  2],
 [211, 11, 632, 9, 25, 55, 2, 381, 36, 10, 109, 718, 10, 55],
 [72, 234, 13, 798, 119, 108, 608, 72, 13, 12, 51, 842, 412, 2, 13, 246],
 [719,
  72,
  4,
  843,
  438,
  235,
  3,
  17,
  108,
  439,
  2,
  150,
  957,
  2,
  124,
  16,
  124,
  413,
  516,
  958,
  581,
  64],
 [136,
  13,
  96,
  682,
  26,
  133,
  6,
  81,
  2,
  488,
  2,
  5,
  323,
  534,
  901,
  36,
  339,
  12,
  47,
  16,
  5,
  96,
  488,
  242,
  47,
  18],
 [30,
  236,
  32,
  77,
  219,
  7,
  1,
  98,
 

In [ ]:
max_len = 50
sequences = sequence.pad_sequences(text_tokenized,maxlen=max_len)

In [ ]:
sequences

array([[  0,   0,   0, ...,  67,  58, 144],
       [  0,   0,   0, ..., 336, 470,   6],
       [  0,   0,   0, ..., 179, 659, 389],
       ...,
       [  0,   0,   0, ...,  23, 105, 250],
       [  0,   0,   0, ..., 200,  12,  47],
       [  0,   0,   0, ...,   2,  61, 268]], dtype=int32)

In [ ]:
# Build model

In [ ]:
model = Sequential()
model.add(Embedding(max_words, 20, input_length=max_len))
model.add(LSTM(64))
model.add(Dense(1, activation="sigmoid"))
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.fit(sequences,Y,batch_size=128,epochs=10,
          validation_split=0.2)

Epoch 1/10
35/35 [==============================] - 7s 111ms/step - loss: 0.4942 - accuracy: 0.8492 - val_loss: 0.3775 - val_accuracy: 0.8700
Epoch 2/10
35/35 [==============================] - 3s 82ms/step - loss: 0.2972 - accuracy: 0.8802 - val_loss: 0.1571 - val_accuracy: 0.9543
Epoch 3/10
35/35 [==============================] - 3s 84ms/step - loss: 0.1076 - accuracy: 0.9729 - val_loss: 0.0762 - val_accuracy: 0.9785
Epoch 4/10
35/35 [==============================] - 3s 82ms/step - loss: 0.0600 - accuracy: 0.9838 - val_loss: 0.0604 - val_accuracy: 0.9848
Epoch 5/10
35/35 [==============================] - 3s 82ms/step - loss: 0.0422 - accuracy: 0.9892 - val_loss: 0.0544 - val_accuracy: 0.9848
Epoch 6/10
35/35 [==============================] - 3s 79ms/step - loss: 0.0330 - accuracy: 0.9917 - val_loss: 0.0519 - val_accuracy: 0.9865
Epoch 7/10
35/35 [==============================] - 3s 82ms/step - loss: 0.0269 - accuracy: 0.9928 - val_loss: 0.0509 - val_accuracy: 0.9874
Epoch 8/10
3

In [ ]:
# Predict on new test data

In [ ]:
inp_test_seq = "WINNER! U win a 500 prize reward & free entry to FA cup final tickets! Text FA to 34212 to receive award"

In [ ]:
test_sequences = mytokenizer.texts_to_sequences(np.array([inp_test_seq]))
test_sequences_matrix = sequence.pad_sequences(test_sequences,maxlen=max_len)

In [ ]:
model.predict(test_sequences_matrix)

1/1 [==============================] - 0s 491ms/step


array([[0.9968965]], dtype=float32)

In [ ]:
import os
MODEL_PATH = os.path.sep.join(['/content/', "SPAM_detector.h5"])
print("[INFO] saving object detector model...")
model.save(MODEL_PATH, save_format="h5")

[INFO] saving object detector model...


In [ ]:
from tensorflow.keras.models import load_model
print("[INFO] loading SPAM detector...")
model2 = load_model(MODEL_PATH)

[INFO] loading SPAM detector...


In [ ]:
model2.predict(test_sequences_matrix)

1/1 [==============================] - 1s 606ms/step


array([[0.9968965]], dtype=float32)

In [ ]:
LB_PATH = os.path.sep.join(['/content/', "tokenizer.pickle"])
f = open(LB_PATH, "wb")
f.write(pickle.dumps(mytokenizer))
f.close()